spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

jwt.secret=${JWT_SECRET}

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
mail.secret=${MAIL_SECRET}

host.deploy.api.server=${HOST_DEPLOY_API_SERVER}
host.develop.api.server=${HOST_DEVELOP_API_SERVER}
host.develop.api.ant-match.uri=${HOST_DEVELOP_API_ANT_MATCH_URI}

oauth2.google.client-id=${OAUTH2_GOOGLE_CLIENT_ID}
oauth2.google.client-secret=${OAUTH2_GOOGLE_CLIENT_SECRET}
oauth2.google.redirect-uri=${OAUTH2_GOOGLE_REDIRECT_URI}
oauth2.google.token-uri=${OAUTH2_GOOGLE_TOKEN_URI}
oauth2.google.resource-uri=${OAUTH2_GOOGLE_RESOURCE_URI}

oauth2.kakao.client-id=${OAUTH2_KAKAO_CLIENT_ID}
oauth2.kakao.redirect-uri=${OAUTH2_KAKAO_REDIRECT_URI}
oauth2.kakao.token-uri=${OAUTH2_KAKAO_TOKEN_URI}
oauth2.kakao.resource-uri=${OAUTH2_KAKAO_RESOURCE_URI}

oauth2.naver.client-id=${OAUTH2_NAVER_CLIENT_ID}
oauth2.naver.client-secret=${OAUTH2_NAVER_CLIENT_SECRET}
oauth2.naver.redirect-uri=${OAUTH2_NAVER_REDIRECT_URI}
oauth2.naver.token-uri=${OAUTH2_NAVER_TOKEN_URI}
oauth2.naver.resource-uri=${OAUTH2_NAVER_RESOURCE_URI}

oauth2.github.client-id=${OAUTH2_GITHUB_CLIENT_ID}
oauth2.github.client-secret=${OAUTH2_GITHUB_CLIENT_SECRET}
oauth2.github.redirect-uri=${OAUTH2_GITHUB_REDIRECT_URI}
oauth2.github.token-uri=${OAUTH2_GITHUB_TOKEN_URI}
oauth2.github.resource-uri=${OAUTH2_GITHUB_RESOURCE_URI}
