name: Spring App CI/CD For Merge

on:
  push:
    branches:
      master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ORGNIZATIONS }}/pol-back:${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_ORGNIZATIONS }}/pol-back:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker for GKE
        run: gcloud auth configure-docker --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT }}

      - name: Deploy to GKE
        run: |
          kubectl set env deployment/pol-back \
            SPRING_PROFILES_ACTIVE=develop \
            LOGGING_FILE_NAME=/app/logs/pol-back.log \
            DB_URL='${{ secrets.DB_URL }}' \
            DB_USERNAME='${{ secrets.DB_USERNAME }}' \
            DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            MAIL_SECRET='${{ secrets.MAIL_SECRET }}' \
            SPRING_MAIL_HOST='${{ secrets.SPRING_MAIL_HOST }}' \
            SPRING_MAIL_PORT='${{ secrets.SPRING_MAIL_PORT }}' \
            SPRING_MAIL_USERNAME='${{ secrets.SPRING_MAIL_USERNAME }}' \
            SPRING_MAIL_PASSWORD='${{ secrets.SPRING_MAIL_PASSWORD }}' \
            SPRING_MAIL_SMTP_AUTH='${{ secrets.SPRING_MAIL_SMTP_AUTH }}' \
            SPRING_MAIL_SMTP_STARTTLS_ENABLE='${{ secrets.SPRING_MAIL_SMTP_STARTTLS_ENABLE }}' \
            HOST_DEPLOY_API_SERVER='${{ secrets.HOST_DEPLOY_API_SERVER }}' \
            HOST_DEVELOP_API_SERVER='${{ secrets.HOST_DEVELOP_API_SERVER }}' \
            HOST_DEVELOP_API_ANT_MATCH_URI='${{ secrets.HOST_DEVELOP_API_ANT_MATCH_URI }}' \
            OAUTH2_GOOGLE_CLIENT_ID='${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}' \
            OAUTH2_GOOGLE_CLIENT_SECRET='${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}' \
            OAUTH2_GOOGLE_REDIRECT_URI='${{ secrets.OAUTH2_GOOGLE_REDIRECT_URI }}' \
            OAUTH2_GOOGLE_TOKEN_URI='${{ secrets.OAUTH2_GOOGLE_TOKEN_URI }}' \
            OAUTH2_GOOGLE_RESOURCE_URI='${{ secrets.OAUTH2_GOOGLE_RESOURCE_URI }}' \
            OAUTH2_KAKAO_CLIENT_ID='${{ secrets.OAUTH2_KAKAO_CLIENT_ID }}' \
            OAUTH2_KAKAO_REDIRECT_URI='${{ secrets.OAUTH2_KAKAO_REDIRECT_URI }}' \
            OAUTH2_KAKAO_TOKEN_URI='${{ secrets.OAUTH2_KAKAO_TOKEN_URI }}' \
            OAUTH2_KAKAO_RESOURCE_URI='${{ secrets.OAUTH2_KAKAO_RESOURCE_URI }}' \
            OAUTH2_NAVER_CLIENT_ID='${{ secrets.OAUTH2_NAVER_CLIENT_ID }}' \
            OAUTH2_NAVER_CLIENT_SECRET='${{ secrets.OAUTH2_NAVER_CLIENT_SECRET }}' \
            OAUTH2_NAVER_REDIRECT_URI='${{ secrets.OAUTH2_NAVER_REDIRECT_URI }}' \
            OAUTH2_NAVER_TOKEN_URI='${{ secrets.OAUTH2_NAVER_TOKEN_URI }}' \
            OAUTH2_NAVER_RESOURCE_URI='${{ secrets.OAUTH2_NAVER_RESOURCE_URI }}' \
            OAUTH2_GITHUB_CLIENT_ID='${{ secrets.OAUTH2_GITHUB_CLIENT_ID }}' \
            OAUTH2_GITHUB_CLIENT_SECRET='${{ secrets.OAUTH2_GITHUB_CLIENT_SECRET }}' \
            OAUTH2_GITHUB_REDIRECT_URI='${{ secrets.OAUTH2_GITHUB_REDIRECT_URI }}' \
            OAUTH2_GITHUB_TOKEN_URI='${{ secrets.OAUTH2_GITHUB_TOKEN_URI }}' \
            OAUTH2_GITHUB_RESOURCE_URI='${{ secrets.OAUTH2_GITHUB_RESOURCE_URI }}'
          kubectl set image deployment/pol-back pol-back=${{ secrets.DOCKERHUB_ORGNIZATIONS }}/pol-back:${{ github.sha }} --record
